coordinator=false
node-scheduler.include-coordinator=false

http-server.https.enabled=true
http-server.process-forwarded=true
internal-communication.https.required=true
#http-server.authentication.allow-insecure-over-http=true
http-server.http.port=7071
#discovery.uri=http://localhost:8080
http-server.https.port=7070
http-server.https.keystore.path=/etc/trino/security/certs/keystore.p12
http-server.https.keystore.key=my-pass

http-server.authentication.type=PASSWORD
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}

discovery.uri=https://trino-master.retail-lake.domain:7070
#case-insensitive-name-matching=true
enable-dynamic-filtering=true


# # Tổng memory user có thể dùng (per node)
# query.max-memory-per-node=${ENV:TRINO_CONF_QUERY_MAX_MEMORY_PER_NODE}

# # Chừa lại một phần heap cho GC, internal buffers
# memory.heap-headroom-per-node=${ENV:TRINO_CONF_MEMORY_HEAP_HEADROOM_PER_NODE}

# # Giới hạn mỗi query (trên toàn cluster, không chỉ 1 node)
# query.max-memory=${ENV:TRINO_CONF_QUERY_MAX_MEMORY}
# query.max-total-memory=${ENV:TRINO_CONF_QUERY_TOTAL_MEMORY}